---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/products":
    get:
      summary: list products
      operationId: listProducts
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example_0:
                  value:
                  - id: 11kdkk111
                    code: MUG
                    name: Reedsy Mug
                    price: '6.00'
                    created_at: '2023-09-18T17:15:35Z'
                    updated_at: '2023-09-18T17:15:35Z'
                  - id: 31kdkk222
                    code: TSHIRT
                    name: Reedsy T-shirt
                    price: '15.00'
                    created_at: '2023-09-18T17:15:35Z'
                    updated_at: '2023-09-18T17:15:35Z'
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
