---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/cart":
    post:
      summary: add items to cart
      operationId: addToCart
      parameters:
        - in: body
          name: products
          required: true
          schema:
            type: object
            properties:
              products:
                type: array
                items:
                  type: object
                  properties:
                    product_id:
                      type: string
                      example: '11kdkk111'
                    quantity:
                      type: integer
                      example: 2
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example_0:
                  value:
                    products:
                    - id: 11kdkk111
                      code: MUG
                      name: Reedsy Mug
                      price: '6.00'
                      quantity: 2
                    - id: 31kdkk222
                      code: TSHIRT
                      name: Reedsy T-shirt
                      price: '15.00'
                      quantity: 1
                    total_price: '27.00'
        '404':
          description: not found
          content:
            application/json:
              examples:
                example_0:
                  value:
                    error: Product not found
        '400':
          description: bad request
          content:
            application/json:
              examples:
                example_0:
                  value:
                    error: Invalid request parameters
  "/api/products":
    get:
      summary: list products
      operationId: listProducts
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example_0:
                  value:
                  - id: 11kdkk111
                    code: MUG
                    name: Reedsy Mug
                    price: '6.00'
                    created_at: '2023-09-18T17:15:35Z'
                    updated_at: '2023-09-18T17:15:35Z'
                  - id: 31kdkk222
                    code: TSHIRT
                    name: Reedsy T-shirt
                    price: '15.00'
                    created_at: '2023-09-18T17:15:35Z'
                    updated_at: '2023-09-18T17:15:35Z'
  "/api/products/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    - name: product
      in: body
      required: true
      schema:
        type: object
        properties:
          product:
            type: object
            properties:
              price:
                type: number
            required:
              - price
        examples:
        example_1:
          value:
            product:
              price: 11.00
    put:
      summary: update product price
      operationId: updateProductPrice
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example_0:
                  value:
                    id: 11kdkk111
                    code: MUG
                    name: Reedsy Mug
                    price: '11.99'
                    created_at: '2023-09-18T17:15:35Z'
                    updated_at: '2023-09-18T17:15:35Z'
        '404':
          description: not found
          content:
            application/json:
              examples:
                example_0:
                  value:
                    error: Product not found
        '400':
          description: bad request
          content:
            application/json:
              examples:
                example_0:
                  value:
                    error: Price must be a positive number
servers:
  - url: http://localhost:3000
    variables:
      defaultHost:
        default: localhost:3000